version: "3"
services:
  spark-master:
    image: spark-master:latest
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./notebooks:/home/jovyan/notebooks
       - ./data:/home/jovyan/notebooks/data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker:
    image: spark-worker:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
    volumes:
       - ./notebooks:/home/jovyan/notebooks
       - ./data:/home/jovyan/notebooks/data
  spark-notebook:
    image: jupyter-notebook:latest
    depends_on:
      - spark-worker
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
       - ./notebooks:/home/jovyan/notebooks
       - ./data:/home/jovyan/notebooks/data
